// Supabase Auth "Send Email" hook — replaces Supabase's own (unreliable,
// wrong-sender-domain) mailer for every authentication email with a direct
// call to the Resend API, using the same sender/domain already verified
// (SPF+DKIM) for every other transactional email in this app (see
// src/lib/resend.ts). Once this hook is enabled in the Supabase dashboard,
// Supabase stops sending auth emails itself entirely — ALL of signup,
// recovery, magiclink (also used for the patient email-code lookup, see
// src/repositories/authRepository.ts), invite and email_change go through
// this function. So every type below has to be handled: silently missing
// one would silently break that flow (e.g. driver signup confirmation,
// password reset) instead of just falling back to Supabase's mailer.
//
// Payload + signature verification follow Supabase's documented "Send
// Email Hook" contract: https://supabase.com/docs/guides/auth/auth-hooks/send-email-hook
//
// Required function secrets (set via `supabase secrets set`, not doable
// from this repo/MCP — see README note below):
//   RESEND_API_KEY          — same key already used by the app's backend
//   SEND_EMAIL_HOOK_SECRET  — generated by Supabase when the hook is
//                              enabled in Dashboard > Authentication > Hooks,
//                              looks like "v1,whsec_<base64>"
// Optional:
//   RESEND_FROM_EMAIL       — defaults to the same address as the rest of
//                              the app (src/lib/resend.ts)

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { Webhook } from "https://esm.sh/standardwebhooks@1.0.0";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
const HOOK_SECRET = Deno.env.get("SEND_EMAIL_HOOK_SECRET")?.replace("v1,whsec_", "");
const FROM_EMAIL = Deno.env.get("RESEND_FROM_EMAIL") || "Docteur Taxi <reservations@docteurtaxi.fr>";
const SUPPORT_EMAIL = "contact@mon-taxi-sante.com";
const SUPPORT_PHONE_DISPLAY = "06 02 12 19 07";
const SUPPORT_PHONE_TEL = "+33602121907";

interface HookUser {
  email: string;
  new_email?: string;
}

interface HookEmailData {
  token: string;
  token_hash: string;
  redirect_to: string;
  email_action_type: string;
  site_url: string;
  token_new: string;
  token_hash_new: string;
}

interface HookPayload {
  user: HookUser;
  email_data: HookEmailData;
}

// GoTrue's own verify endpoint — same one Supabase's default mailer links
// to, reconstructed here since the hook only gives us the token hash, not
// a ready-made URL. PROJECT_REF is stable per Supabase project (not a
// secret — it's the same value already embedded in VITE_SUPABASE_URL).
const PROJECT_REF = "jndiuqemysussvdiwcrk";

function confirmationUrl(tokenHash: string, type: string, redirectTo: string): string {
  const params = new URLSearchParams({ token: tokenHash, type, redirect_to: redirectTo });
  return `https://${PROJECT_REF}.supabase.co/auth/v1/verify?${params.toString()}`;
}

function shell(opts: {
  emoji: string;
  heading: string;
  badge: string;
  badgeBg: string;
  badgeColor: string;
  intro: string;
  cta:
    | { kind: "button"; label: string; url: string }
    | { kind: "code"; value: string };
  footnote: string;
}): string {
  const ctaHtml =
    opts.cta.kind === "button"
      ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:28px 0;">
           <tr>
             <td align="center">
               <a href="${opts.cta.url}" style="background:#1244E8;color:#fff;text-decoration:none;font-weight:700;font-size:15px;padding:14px 32px;border-radius:10px;display:inline-block;">${opts.cta.label}</a>
             </td>
           </tr>
         </table>`
      : `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:28px 0;">
           <tr>
             <td align="center" style="background:#EFF4FF;border-radius:10px;padding:18px 24px;">
               <span style="font-size:32px;font-weight:700;letter-spacing:0.3em;color:#1244E8;">${opts.cta.value}</span>
             </td>
           </tr>
         </table>`;

  return `<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${opts.heading}</title>
  </head>
  <body style="margin:0;padding:24px 16px;background:#F7F8FC;font-family:-apple-system,Helvetica,Arial,sans-serif;color:#0B0F1C;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;margin:0 auto;border-collapse:collapse;">
      <tr>
        <td style="background:#1244E8;color:#fff;padding:28px 24px;border-radius:14px 14px 0 0;">
          <p style="margin:0;font-size:12px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;opacity:0.85;">Docteur Taxi</p>
          <h1 style="margin:10px 0 0;font-size:21px;line-height:1.35;">
            <span style="font-size:20px;vertical-align:-2px;">${opts.emoji}</span>&nbsp; ${opts.heading}
          </h1>
        </td>
      </tr>
      <tr>
        <td style="background:#fff;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 14px 14px;padding:28px 24px;">
          <span style="display:inline-block;background:${opts.badgeBg};color:${opts.badgeColor};font-size:12px;font-weight:700;padding:5px 12px;border-radius:999px;margin-bottom:16px;">${opts.badge}</span>
          <p style="margin:0 0 16px;font-size:15px;line-height:1.5;">Bonjour,</p>
          <p style="margin:0 0 16px;font-size:15px;line-height:1.5;">${opts.intro}</p>
          ${ctaHtml}
          <p style="margin:0;font-size:13px;color:#6b7280;line-height:1.5;">${opts.footnote}</p>
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:28px;border-top:1px solid #f1f2f6;">
            <tr>
              <td style="padding-top:18px;font-size:13px;color:#6b7280;line-height:1.6;">
                Une question ? Appelez le
                <a href="tel:${SUPPORT_PHONE_TEL}" style="color:#1244E8;font-weight:600;text-decoration:none;">${SUPPORT_PHONE_DISPLAY}</a>
                ou écrivez à
                <a href="mailto:${SUPPORT_EMAIL}" style="color:#1244E8;font-weight:600;text-decoration:none;">${SUPPORT_EMAIL}</a>.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

const ACTION_BADGE = { badge: "Action requise", badgeBg: "#EFF4FF", badgeColor: "#1244E8" };

function renderEmail(user: HookUser, emailData: HookEmailData): { subject: string; to: string; html: string } | null {
  const { email_action_type, redirect_to } = emailData;

  switch (email_action_type) {
    case "signup":
      return {
        subject: "Confirmez votre adresse e-mail — Docteur Taxi",
        to: user.email,
        html: shell({
          emoji: "✉️",
          heading: "Confirmez votre adresse e-mail",
          ...ACTION_BADGE,
          intro: "Merci de votre inscription sur Docteur Taxi. Confirmez votre adresse e-mail pour activer votre compte.",
          cta: {
            kind: "button",
            label: "Confirmer mon adresse e-mail",
            url: confirmationUrl(emailData.token_hash, email_action_type, redirect_to),
          },
          footnote: "Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer cet e-mail.",
        }),
      };

    case "recovery":
      return {
        subject: "Réinitialisez votre mot de passe — Docteur Taxi",
        to: user.email,
        html: shell({
          emoji: "🔑",
          heading: "Réinitialisez votre mot de passe",
          ...ACTION_BADGE,
          intro:
            "Vous avez demandé la réinitialisation de votre mot de passe Docteur Taxi. Cliquez sur le bouton ci-dessous pour choisir un nouveau mot de passe.",
          cta: {
            kind: "button",
            label: "Réinitialiser mon mot de passe",
            url: confirmationUrl(emailData.token_hash, email_action_type, redirect_to),
          },
          footnote:
            "Ce lien est valable une heure. Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer cet e-mail — votre mot de passe ne sera pas modifié.",
        }),
      };

    case "magiclink":
      // Also the type used for signInWithOtp email codes (patient history
      // lookup, PatientEmailLogin.tsx) — not just true magic links.
      return {
        subject: "Votre code de connexion — Docteur Taxi",
        to: user.email,
        html: shell({
          emoji: "🔑",
          heading: "Votre code de connexion",
          ...ACTION_BADGE,
          intro:
            "Saisissez ce code sur la page où vous avez demandé à vous connecter ou à retrouver votre historique de réservations Docteur Taxi.",
          cta: { kind: "code", value: emailData.token },
          footnote:
            "Ce code expire dans quelques minutes. Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer cet e-mail.",
        }),
      };

    case "invite":
      return {
        subject: "Vous êtes invité(e) sur Docteur Taxi",
        to: user.email,
        html: shell({
          emoji: "🎉",
          heading: "Vous êtes invité(e)",
          badge: "Invitation",
          badgeBg: "#ECFDF5",
          badgeColor: "#059669",
          intro:
            "Vous avez été invité(e) à créer un compte sur Docteur Taxi. Cliquez sur le bouton ci-dessous pour choisir votre mot de passe et accéder à votre espace.",
          cta: {
            kind: "button",
            label: "Créer mon mot de passe",
            url: confirmationUrl(emailData.token_hash, email_action_type, redirect_to),
          },
          footnote: "Si vous ne vous attendiez pas à cette invitation, vous pouvez ignorer cet e-mail.",
        }),
      };

    case "email_change": {
      // Secure Email Change setting (Dashboard > Authentication > Providers)
      // decides whether one or two OTPs are issued — see the field-naming
      // caveat in Supabase's Send Email Hook docs: token_hash_new pairs
      // with the CURRENT email, token_hash pairs with the NEW one. This app
      // has no email-change UI today (only password updates, see
      // authRepository.ts), so this path isn't exercised in practice —
      // handled defensively so it doesn't silently break if that ever
      // changes.
      const toNewEmail = Boolean(emailData.token_hash);
      const to = toNewEmail ? user.new_email || user.email : user.email;
      const tokenHash = toNewEmail ? emailData.token_hash : emailData.token_hash_new;
      if (!to || !tokenHash) return null;
      return {
        subject: "Confirmez votre nouvelle adresse e-mail — Docteur Taxi",
        to,
        html: shell({
          emoji: "📧",
          heading: "Confirmez votre nouvelle adresse e-mail",
          ...ACTION_BADGE,
          intro: `Vous avez demandé à remplacer l'adresse e-mail de votre compte Docteur Taxi par <strong>${
            user.new_email || ""
          }</strong>. Confirmez ce changement en cliquant sur le bouton ci-dessous.`,
          cta: {
            kind: "button",
            label: "Confirmer la nouvelle adresse",
            url: confirmationUrl(tokenHash, email_action_type, redirect_to),
          },
          footnote:
            "Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer cet e-mail — votre adresse actuelle restera inchangée.",
        }),
      };
    }

    default:
      // Notification-only types (reauthentication, password_changed_notification,
      // *_notification...) aren't triggered by any flow in this app (no MFA,
      // no reauthentication) — unhandled on purpose so a future use shows up
      // as a clear failure instead of a silently missing email.
      return null;
  }
}

Deno.serve(async (req) => {
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  if (!RESEND_API_KEY || !HOOK_SECRET) {
    return new Response(
      JSON.stringify({ error: { message: "Missing RESEND_API_KEY or SEND_EMAIL_HOOK_SECRET secret" } }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }

  const payload = await req.text();
  const headers = Object.fromEntries(req.headers);

  let data: HookPayload;
  try {
    data = new Webhook(HOOK_SECRET).verify(payload, headers) as HookPayload;
  } catch {
    return new Response(JSON.stringify({ error: { message: "Invalid signature" } }), {
      status: 401,
      headers: { "Content-Type": "application/json" },
    });
  }

  const email = renderEmail(data.user, data.email_data);
  if (!email) {
    return new Response(
      JSON.stringify({ error: { message: `Unsupported email_action_type: ${data.email_data.email_action_type}` } }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({ from: FROM_EMAIL, to: [email.to], subject: email.subject, html: email.html }),
    });
    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Resend API ${res.status}: ${text}`);
    }
  } catch (err) {
    return new Response(
      JSON.stringify({ error: { message: err instanceof Error ? err.message : String(err) } }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }

  return new Response(JSON.stringify({}), { status: 200, headers: { "Content-Type": "application/json" } });
});
