/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsCpamRouteImport } from './routes/tarifs-cpam'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationIndexRouteImport } from './routes/reservation/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TableauDeBordChauffeurRouteImport } from './routes/tableau-de-bord/chauffeur'
import { Route as ChauffeursTarifsRouteImport } from './routes/chauffeurs/tarifs'
import { Route as ChauffeursInscriptionRouteImport } from './routes/chauffeurs/inscription'
import { Route as BlogTransportCpamRouteImport } from './routes/blog/transport-cpam'
import { Route as BlogPmtPrescriptionRouteImport } from './routes/blog/pmt-prescription'
import { Route as BlogAldTransportRouteImport } from './routes/blog/ald-transport'
import { Route as DepartmentCityRouteImport } from './routes/$department.$city'

const TarifsCpamRoute = TarifsCpamRouteImport.update({
  id: '/tarifs-cpam',
  path: '/tarifs-cpam',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIndexRoute = ReservationIndexRouteImport.update({
  id: '/reservation/',
  path: '/reservation/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordChauffeurRoute = TableauDeBordChauffeurRouteImport.update({
  id: '/tableau-de-bord/chauffeur',
  path: '/tableau-de-bord/chauffeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursTarifsRoute = ChauffeursTarifsRouteImport.update({
  id: '/chauffeurs/tarifs',
  path: '/chauffeurs/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursInscriptionRoute = ChauffeursInscriptionRouteImport.update({
  id: '/chauffeurs/inscription',
  path: '/chauffeurs/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTransportCpamRoute = BlogTransportCpamRouteImport.update({
  id: '/blog/transport-cpam',
  path: '/blog/transport-cpam',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPmtPrescriptionRoute = BlogPmtPrescriptionRouteImport.update({
  id: '/blog/pmt-prescription',
  path: '/blog/pmt-prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAldTransportRoute = BlogAldTransportRouteImport.update({
  id: '/blog/ald-transport',
  path: '/blog/ald-transport',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentCityRoute = DepartmentCityRouteImport.update({
  id: '/$department/$city',
  path: '/$department/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs-cpam': typeof TarifsCpamRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/blog/ald-transport': typeof BlogAldTransportRoute
  '/blog/pmt-prescription': typeof BlogPmtPrescriptionRoute
  '/blog/transport-cpam': typeof BlogTransportCpamRoute
  '/chauffeurs/inscription': typeof ChauffeursInscriptionRoute
  '/chauffeurs/tarifs': typeof ChauffeursTarifsRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/blog': typeof BlogIndexRoute
  '/reservation': typeof ReservationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs-cpam': typeof TarifsCpamRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/blog/ald-transport': typeof BlogAldTransportRoute
  '/blog/pmt-prescription': typeof BlogPmtPrescriptionRoute
  '/blog/transport-cpam': typeof BlogTransportCpamRoute
  '/chauffeurs/inscription': typeof ChauffeursInscriptionRoute
  '/chauffeurs/tarifs': typeof ChauffeursTarifsRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/blog': typeof BlogIndexRoute
  '/reservation': typeof ReservationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cgv': typeof CgvRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs-cpam': typeof TarifsCpamRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/blog/ald-transport': typeof BlogAldTransportRoute
  '/blog/pmt-prescription': typeof BlogPmtPrescriptionRoute
  '/blog/transport-cpam': typeof BlogTransportCpamRoute
  '/chauffeurs/inscription': typeof ChauffeursInscriptionRoute
  '/chauffeurs/tarifs': typeof ChauffeursTarifsRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/blog/': typeof BlogIndexRoute
  '/reservation/': typeof ReservationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cgv'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/connexion'
    | '/faq'
    | '/mentions-legales'
    | '/tarifs-cpam'
    | '/$department/$city'
    | '/blog/ald-transport'
    | '/blog/pmt-prescription'
    | '/blog/transport-cpam'
    | '/chauffeurs/inscription'
    | '/chauffeurs/tarifs'
    | '/tableau-de-bord/chauffeur'
    | '/blog'
    | '/reservation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cgv'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/connexion'
    | '/faq'
    | '/mentions-legales'
    | '/tarifs-cpam'
    | '/$department/$city'
    | '/blog/ald-transport'
    | '/blog/pmt-prescription'
    | '/blog/transport-cpam'
    | '/chauffeurs/inscription'
    | '/chauffeurs/tarifs'
    | '/tableau-de-bord/chauffeur'
    | '/blog'
    | '/reservation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cgv'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/connexion'
    | '/faq'
    | '/mentions-legales'
    | '/tarifs-cpam'
    | '/$department/$city'
    | '/blog/ald-transport'
    | '/blog/pmt-prescription'
    | '/blog/transport-cpam'
    | '/chauffeurs/inscription'
    | '/chauffeurs/tarifs'
    | '/tableau-de-bord/chauffeur'
    | '/blog/'
    | '/reservation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CgvRoute: typeof CgvRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  TarifsCpamRoute: typeof TarifsCpamRoute
  DepartmentCityRoute: typeof DepartmentCityRoute
  BlogAldTransportRoute: typeof BlogAldTransportRoute
  BlogPmtPrescriptionRoute: typeof BlogPmtPrescriptionRoute
  BlogTransportCpamRoute: typeof BlogTransportCpamRoute
  ChauffeursInscriptionRoute: typeof ChauffeursInscriptionRoute
  ChauffeursTarifsRoute: typeof ChauffeursTarifsRoute
  TableauDeBordChauffeurRoute: typeof TableauDeBordChauffeurRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs-cpam': {
      id: '/tarifs-cpam'
      path: '/tarifs-cpam'
      fullPath: '/tarifs-cpam'
      preLoaderRoute: typeof TarifsCpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord/chauffeur': {
      id: '/tableau-de-bord/chauffeur'
      path: '/tableau-de-bord/chauffeur'
      fullPath: '/tableau-de-bord/chauffeur'
      preLoaderRoute: typeof TableauDeBordChauffeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs/tarifs': {
      id: '/chauffeurs/tarifs'
      path: '/chauffeurs/tarifs'
      fullPath: '/chauffeurs/tarifs'
      preLoaderRoute: typeof ChauffeursTarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs/inscription': {
      id: '/chauffeurs/inscription'
      path: '/chauffeurs/inscription'
      fullPath: '/chauffeurs/inscription'
      preLoaderRoute: typeof ChauffeursInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/transport-cpam': {
      id: '/blog/transport-cpam'
      path: '/blog/transport-cpam'
      fullPath: '/blog/transport-cpam'
      preLoaderRoute: typeof BlogTransportCpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/pmt-prescription': {
      id: '/blog/pmt-prescription'
      path: '/blog/pmt-prescription'
      fullPath: '/blog/pmt-prescription'
      preLoaderRoute: typeof BlogPmtPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ald-transport': {
      id: '/blog/ald-transport'
      path: '/blog/ald-transport'
      fullPath: '/blog/ald-transport'
      preLoaderRoute: typeof BlogAldTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$department/$city': {
      id: '/$department/$city'
      path: '/$department/$city'
      fullPath: '/$department/$city'
      preLoaderRoute: typeof DepartmentCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CgvRoute: CgvRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  TarifsCpamRoute: TarifsCpamRoute,
  DepartmentCityRoute: DepartmentCityRoute,
  BlogAldTransportRoute: BlogAldTransportRoute,
  BlogPmtPrescriptionRoute: BlogPmtPrescriptionRoute,
  BlogTransportCpamRoute: BlogTransportCpamRoute,
  ChauffeursInscriptionRoute: ChauffeursInscriptionRoute,
  ChauffeursTarifsRoute: ChauffeursTarifsRoute,
  TableauDeBordChauffeurRoute: TableauDeBordChauffeurRoute,
  BlogIndexRoute: BlogIndexRoute,
  ReservationIndexRoute: ReservationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
