/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillesRouteImport } from './routes/villes'
import { Route as TarifsCpamRouteImport } from './routes/tarifs-cpam'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as MesReservationsRouteImport } from './routes/mes-reservations'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConfirmerTrajetRouteImport } from './routes/confirmer-trajet'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationIndexRouteImport } from './routes/reservation/index'
import { Route as MaladiesIndexRouteImport } from './routes/maladies.index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DepartmentIndexRouteImport } from './routes/$department.index'
import { Route as TableauDeBordChauffeurRouteImport } from './routes/tableau-de-bord/chauffeur'
import { Route as ReservationConfirmationRouteImport } from './routes/reservation/confirmation'
import { Route as MaladiesAldRouteImport } from './routes/maladies.$ald'
import { Route as HopitauxSlugRouteImport } from './routes/hopitaux.$slug'
import { Route as ChauffeursTarifsRouteImport } from './routes/chauffeurs/tarifs'
import { Route as ChauffeursInscriptionRouteImport } from './routes/chauffeurs/inscription'
import { Route as BlogVslOuTaxiConventionneRouteImport } from './routes/blog/vsl-ou-taxi-conventionne'
import { Route as BlogTransportPmrPersonnesAgeesRouteImport } from './routes/blog/transport-pmr-personnes-agees'
import { Route as BlogTransportCpamRouteImport } from './routes/blog/transport-cpam'
import { Route as BlogTraitementsReguliersTaxiConventionneRouteImport } from './routes/blog/traitements-reguliers-taxi-conventionne'
import { Route as BlogTaxiSansPrescriptionRouteImport } from './routes/blog/taxi-sans-prescription'
import { Route as BlogTaxiConventionneSansAvanceFraisRouteImport } from './routes/blog/taxi-conventionne-sans-avance-frais'
import { Route as BlogTaxiConventionneGrossesseRouteImport } from './routes/blog/taxi-conventionne-grossesse'
import { Route as BlogRetourDomicileSortieHopitalRouteImport } from './routes/blog/retour-domicile-sortie-hopital'
import { Route as BlogPmtPrescriptionRouteImport } from './routes/blog/pmt-prescription'
import { Route as BlogAldTransportRouteImport } from './routes/blog/ald-transport'
import { Route as BlogAccompagnantTaxiConventionneRouteImport } from './routes/blog/accompagnant-taxi-conventionne'
import { Route as ApiDriverOfflineBeaconRouteImport } from './routes/api/driver-offline-beacon'
import { Route as AdminConnexionRouteImport } from './routes/admin_.connexion'
import { Route as AdminStatistiquesRouteImport } from './routes/admin/statistiques'
import { Route as AdminSecuriteRouteImport } from './routes/admin/securite'
import { Route as AdminReservationsRouteImport } from './routes/admin/reservations'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as AdminJournalRouteImport } from './routes/admin/journal'
import { Route as AdminChauffeursRouteImport } from './routes/admin/chauffeurs'
import { Route as AdminAvisRouteImport } from './routes/admin/avis'
import { Route as DepartmentCityRouteImport } from './routes/$department.$city'
import { Route as TableauDeBordChauffeurCompteRouteImport } from './routes/tableau-de-bord/chauffeur_.compte'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiCronExpireDriverTrialsRouteImport } from './routes/api/cron/expire-driver-trials'
import { Route as ApiCronExpireBookingsRouteImport } from './routes/api/cron/expire-bookings'
import { Route as ApiCronBookingRemindersRouteImport } from './routes/api/cron/booking-reminders'
import { Route as ApiCronAtRiskBookingsRouteImport } from './routes/api/cron/at-risk-bookings'
import { Route as TableauDeBordChauffeurCourseIdRouteImport } from './routes/tableau-de-bord/chauffeur_.course.$id'

const VillesRoute = VillesRouteImport.update({
  id: '/villes',
  path: '/villes',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsCpamRoute = TarifsCpamRouteImport.update({
  id: '/tarifs-cpam',
  path: '/tarifs-cpam',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const MesReservationsRoute = MesReservationsRouteImport.update({
  id: '/mes-reservations',
  path: '/mes-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmerTrajetRoute = ConfirmerTrajetRouteImport.update({
  id: '/confirmer-trajet',
  path: '/confirmer-trajet',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIndexRoute = ReservationIndexRouteImport.update({
  id: '/reservation/',
  path: '/reservation/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaladiesIndexRoute = MaladiesIndexRouteImport.update({
  id: '/maladies/',
  path: '/maladies/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DepartmentIndexRoute = DepartmentIndexRouteImport.update({
  id: '/$department/',
  path: '/$department/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordChauffeurRoute = TableauDeBordChauffeurRouteImport.update({
  id: '/tableau-de-bord/chauffeur',
  path: '/tableau-de-bord/chauffeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationConfirmationRoute = ReservationConfirmationRouteImport.update({
  id: '/reservation/confirmation',
  path: '/reservation/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const MaladiesAldRoute = MaladiesAldRouteImport.update({
  id: '/maladies/$ald',
  path: '/maladies/$ald',
  getParentRoute: () => rootRouteImport,
} as any)
const HopitauxSlugRoute = HopitauxSlugRouteImport.update({
  id: '/hopitaux/$slug',
  path: '/hopitaux/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursTarifsRoute = ChauffeursTarifsRouteImport.update({
  id: '/chauffeurs/tarifs',
  path: '/chauffeurs/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursInscriptionRoute = ChauffeursInscriptionRouteImport.update({
  id: '/chauffeurs/inscription',
  path: '/chauffeurs/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogVslOuTaxiConventionneRoute =
  BlogVslOuTaxiConventionneRouteImport.update({
    id: '/blog/vsl-ou-taxi-conventionne',
    path: '/blog/vsl-ou-taxi-conventionne',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTransportPmrPersonnesAgeesRoute =
  BlogTransportPmrPersonnesAgeesRouteImport.update({
    id: '/blog/transport-pmr-personnes-agees',
    path: '/blog/transport-pmr-personnes-agees',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTransportCpamRoute = BlogTransportCpamRouteImport.update({
  id: '/blog/transport-cpam',
  path: '/blog/transport-cpam',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTraitementsReguliersTaxiConventionneRoute =
  BlogTraitementsReguliersTaxiConventionneRouteImport.update({
    id: '/blog/traitements-reguliers-taxi-conventionne',
    path: '/blog/traitements-reguliers-taxi-conventionne',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTaxiSansPrescriptionRoute =
  BlogTaxiSansPrescriptionRouteImport.update({
    id: '/blog/taxi-sans-prescription',
    path: '/blog/taxi-sans-prescription',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTaxiConventionneSansAvanceFraisRoute =
  BlogTaxiConventionneSansAvanceFraisRouteImport.update({
    id: '/blog/taxi-conventionne-sans-avance-frais',
    path: '/blog/taxi-conventionne-sans-avance-frais',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTaxiConventionneGrossesseRoute =
  BlogTaxiConventionneGrossesseRouteImport.update({
    id: '/blog/taxi-conventionne-grossesse',
    path: '/blog/taxi-conventionne-grossesse',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRetourDomicileSortieHopitalRoute =
  BlogRetourDomicileSortieHopitalRouteImport.update({
    id: '/blog/retour-domicile-sortie-hopital',
    path: '/blog/retour-domicile-sortie-hopital',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPmtPrescriptionRoute = BlogPmtPrescriptionRouteImport.update({
  id: '/blog/pmt-prescription',
  path: '/blog/pmt-prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAldTransportRoute = BlogAldTransportRouteImport.update({
  id: '/blog/ald-transport',
  path: '/blog/ald-transport',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAccompagnantTaxiConventionneRoute =
  BlogAccompagnantTaxiConventionneRouteImport.update({
    id: '/blog/accompagnant-taxi-conventionne',
    path: '/blog/accompagnant-taxi-conventionne',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDriverOfflineBeaconRoute = ApiDriverOfflineBeaconRouteImport.update({
  id: '/api/driver-offline-beacon',
  path: '/api/driver-offline-beacon',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnexionRoute = AdminConnexionRouteImport.update({
  id: '/admin_/connexion',
  path: '/admin/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatistiquesRoute = AdminStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecuriteRoute = AdminSecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJournalRoute = AdminJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChauffeursRoute = AdminChauffeursRouteImport.update({
  id: '/chauffeurs',
  path: '/chauffeurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisRoute = AdminAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => AdminRoute,
} as any)
const DepartmentCityRoute = DepartmentCityRouteImport.update({
  id: '/$department/$city',
  path: '/$department/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordChauffeurCompteRoute =
  TableauDeBordChauffeurCompteRouteImport.update({
    id: '/tableau-de-bord/chauffeur_/compte',
    path: '/tableau-de-bord/chauffeur/compte',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronExpireDriverTrialsRoute =
  ApiCronExpireDriverTrialsRouteImport.update({
    id: '/api/cron/expire-driver-trials',
    path: '/api/cron/expire-driver-trials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronExpireBookingsRoute = ApiCronExpireBookingsRouteImport.update({
  id: '/api/cron/expire-bookings',
  path: '/api/cron/expire-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBookingRemindersRoute = ApiCronBookingRemindersRouteImport.update({
  id: '/api/cron/booking-reminders',
  path: '/api/cron/booking-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAtRiskBookingsRoute = ApiCronAtRiskBookingsRouteImport.update({
  id: '/api/cron/at-risk-bookings',
  path: '/api/cron/at-risk-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordChauffeurCourseIdRoute =
  TableauDeBordChauffeurCourseIdRouteImport.update({
    id: '/tableau-de-bord/chauffeur_/course/$id',
    path: '/tableau-de-bord/chauffeur/course/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cgv': typeof CgvRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmer-trajet': typeof ConfirmerTrajetRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/tarifs-cpam': typeof TarifsCpamRoute
  '/villes': typeof VillesRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/chauffeurs': typeof AdminChauffeursRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/securite': typeof AdminSecuriteRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/api/driver-offline-beacon': typeof ApiDriverOfflineBeaconRoute
  '/blog/accompagnant-taxi-conventionne': typeof BlogAccompagnantTaxiConventionneRoute
  '/blog/ald-transport': typeof BlogAldTransportRoute
  '/blog/pmt-prescription': typeof BlogPmtPrescriptionRoute
  '/blog/retour-domicile-sortie-hopital': typeof BlogRetourDomicileSortieHopitalRoute
  '/blog/taxi-conventionne-grossesse': typeof BlogTaxiConventionneGrossesseRoute
  '/blog/taxi-conventionne-sans-avance-frais': typeof BlogTaxiConventionneSansAvanceFraisRoute
  '/blog/taxi-sans-prescription': typeof BlogTaxiSansPrescriptionRoute
  '/blog/traitements-reguliers-taxi-conventionne': typeof BlogTraitementsReguliersTaxiConventionneRoute
  '/blog/transport-cpam': typeof BlogTransportCpamRoute
  '/blog/transport-pmr-personnes-agees': typeof BlogTransportPmrPersonnesAgeesRoute
  '/blog/vsl-ou-taxi-conventionne': typeof BlogVslOuTaxiConventionneRoute
  '/chauffeurs/inscription': typeof ChauffeursInscriptionRoute
  '/chauffeurs/tarifs': typeof ChauffeursTarifsRoute
  '/hopitaux/$slug': typeof HopitauxSlugRoute
  '/maladies/$ald': typeof MaladiesAldRoute
  '/reservation/confirmation': typeof ReservationConfirmationRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/$department': typeof DepartmentIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/maladies': typeof MaladiesIndexRoute
  '/reservation': typeof ReservationIndexRoute
  '/api/cron/at-risk-bookings': typeof ApiCronAtRiskBookingsRoute
  '/api/cron/booking-reminders': typeof ApiCronBookingRemindersRoute
  '/api/cron/expire-bookings': typeof ApiCronExpireBookingsRoute
  '/api/cron/expire-driver-trials': typeof ApiCronExpireDriverTrialsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/tableau-de-bord/chauffeur/compte': typeof TableauDeBordChauffeurCompteRoute
  '/tableau-de-bord/chauffeur/course/$id': typeof TableauDeBordChauffeurCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmer-trajet': typeof ConfirmerTrajetRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/tarifs-cpam': typeof TarifsCpamRoute
  '/villes': typeof VillesRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/chauffeurs': typeof AdminChauffeursRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/securite': typeof AdminSecuriteRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/api/driver-offline-beacon': typeof ApiDriverOfflineBeaconRoute
  '/blog/accompagnant-taxi-conventionne': typeof BlogAccompagnantTaxiConventionneRoute
  '/blog/ald-transport': typeof BlogAldTransportRoute
  '/blog/pmt-prescription': typeof BlogPmtPrescriptionRoute
  '/blog/retour-domicile-sortie-hopital': typeof BlogRetourDomicileSortieHopitalRoute
  '/blog/taxi-conventionne-grossesse': typeof BlogTaxiConventionneGrossesseRoute
  '/blog/taxi-conventionne-sans-avance-frais': typeof BlogTaxiConventionneSansAvanceFraisRoute
  '/blog/taxi-sans-prescription': typeof BlogTaxiSansPrescriptionRoute
  '/blog/traitements-reguliers-taxi-conventionne': typeof BlogTraitementsReguliersTaxiConventionneRoute
  '/blog/transport-cpam': typeof BlogTransportCpamRoute
  '/blog/transport-pmr-personnes-agees': typeof BlogTransportPmrPersonnesAgeesRoute
  '/blog/vsl-ou-taxi-conventionne': typeof BlogVslOuTaxiConventionneRoute
  '/chauffeurs/inscription': typeof ChauffeursInscriptionRoute
  '/chauffeurs/tarifs': typeof ChauffeursTarifsRoute
  '/hopitaux/$slug': typeof HopitauxSlugRoute
  '/maladies/$ald': typeof MaladiesAldRoute
  '/reservation/confirmation': typeof ReservationConfirmationRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/$department': typeof DepartmentIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/maladies': typeof MaladiesIndexRoute
  '/reservation': typeof ReservationIndexRoute
  '/api/cron/at-risk-bookings': typeof ApiCronAtRiskBookingsRoute
  '/api/cron/booking-reminders': typeof ApiCronBookingRemindersRoute
  '/api/cron/expire-bookings': typeof ApiCronExpireBookingsRoute
  '/api/cron/expire-driver-trials': typeof ApiCronExpireDriverTrialsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/tableau-de-bord/chauffeur/compte': typeof TableauDeBordChauffeurCompteRoute
  '/tableau-de-bord/chauffeur/course/$id': typeof TableauDeBordChauffeurCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cgv': typeof CgvRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmer-trajet': typeof ConfirmerTrajetRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/tarifs-cpam': typeof TarifsCpamRoute
  '/villes': typeof VillesRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/chauffeurs': typeof AdminChauffeursRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/securite': typeof AdminSecuriteRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin_/connexion': typeof AdminConnexionRoute
  '/api/driver-offline-beacon': typeof ApiDriverOfflineBeaconRoute
  '/blog/accompagnant-taxi-conventionne': typeof BlogAccompagnantTaxiConventionneRoute
  '/blog/ald-transport': typeof BlogAldTransportRoute
  '/blog/pmt-prescription': typeof BlogPmtPrescriptionRoute
  '/blog/retour-domicile-sortie-hopital': typeof BlogRetourDomicileSortieHopitalRoute
  '/blog/taxi-conventionne-grossesse': typeof BlogTaxiConventionneGrossesseRoute
  '/blog/taxi-conventionne-sans-avance-frais': typeof BlogTaxiConventionneSansAvanceFraisRoute
  '/blog/taxi-sans-prescription': typeof BlogTaxiSansPrescriptionRoute
  '/blog/traitements-reguliers-taxi-conventionne': typeof BlogTraitementsReguliersTaxiConventionneRoute
  '/blog/transport-cpam': typeof BlogTransportCpamRoute
  '/blog/transport-pmr-personnes-agees': typeof BlogTransportPmrPersonnesAgeesRoute
  '/blog/vsl-ou-taxi-conventionne': typeof BlogVslOuTaxiConventionneRoute
  '/chauffeurs/inscription': typeof ChauffeursInscriptionRoute
  '/chauffeurs/tarifs': typeof ChauffeursTarifsRoute
  '/hopitaux/$slug': typeof HopitauxSlugRoute
  '/maladies/$ald': typeof MaladiesAldRoute
  '/reservation/confirmation': typeof ReservationConfirmationRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/$department/': typeof DepartmentIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/maladies/': typeof MaladiesIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/api/cron/at-risk-bookings': typeof ApiCronAtRiskBookingsRoute
  '/api/cron/booking-reminders': typeof ApiCronBookingRemindersRoute
  '/api/cron/expire-bookings': typeof ApiCronExpireBookingsRoute
  '/api/cron/expire-driver-trials': typeof ApiCronExpireDriverTrialsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/tableau-de-bord/chauffeur_/compte': typeof TableauDeBordChauffeurCompteRoute
  '/tableau-de-bord/chauffeur_/course/$id': typeof TableauDeBordChauffeurCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cgv'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/confirmer-trajet'
    | '/connexion'
    | '/faq'
    | '/mentions-legales'
    | '/mes-reservations'
    | '/mot-de-passe-oublie'
    | '/reinitialiser-mot-de-passe'
    | '/tarifs-cpam'
    | '/villes'
    | '/$department/$city'
    | '/admin/avis'
    | '/admin/chauffeurs'
    | '/admin/journal'
    | '/admin/parametres'
    | '/admin/patients'
    | '/admin/reservations'
    | '/admin/securite'
    | '/admin/statistiques'
    | '/admin/connexion'
    | '/api/driver-offline-beacon'
    | '/blog/accompagnant-taxi-conventionne'
    | '/blog/ald-transport'
    | '/blog/pmt-prescription'
    | '/blog/retour-domicile-sortie-hopital'
    | '/blog/taxi-conventionne-grossesse'
    | '/blog/taxi-conventionne-sans-avance-frais'
    | '/blog/taxi-sans-prescription'
    | '/blog/traitements-reguliers-taxi-conventionne'
    | '/blog/transport-cpam'
    | '/blog/transport-pmr-personnes-agees'
    | '/blog/vsl-ou-taxi-conventionne'
    | '/chauffeurs/inscription'
    | '/chauffeurs/tarifs'
    | '/hopitaux/$slug'
    | '/maladies/$ald'
    | '/reservation/confirmation'
    | '/tableau-de-bord/chauffeur'
    | '/$department'
    | '/admin/'
    | '/blog'
    | '/maladies'
    | '/reservation'
    | '/api/cron/at-risk-bookings'
    | '/api/cron/booking-reminders'
    | '/api/cron/expire-bookings'
    | '/api/cron/expire-driver-trials'
    | '/api/webhooks/stripe'
    | '/tableau-de-bord/chauffeur/compte'
    | '/tableau-de-bord/chauffeur/course/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgv'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/confirmer-trajet'
    | '/connexion'
    | '/faq'
    | '/mentions-legales'
    | '/mes-reservations'
    | '/mot-de-passe-oublie'
    | '/reinitialiser-mot-de-passe'
    | '/tarifs-cpam'
    | '/villes'
    | '/$department/$city'
    | '/admin/avis'
    | '/admin/chauffeurs'
    | '/admin/journal'
    | '/admin/parametres'
    | '/admin/patients'
    | '/admin/reservations'
    | '/admin/securite'
    | '/admin/statistiques'
    | '/admin/connexion'
    | '/api/driver-offline-beacon'
    | '/blog/accompagnant-taxi-conventionne'
    | '/blog/ald-transport'
    | '/blog/pmt-prescription'
    | '/blog/retour-domicile-sortie-hopital'
    | '/blog/taxi-conventionne-grossesse'
    | '/blog/taxi-conventionne-sans-avance-frais'
    | '/blog/taxi-sans-prescription'
    | '/blog/traitements-reguliers-taxi-conventionne'
    | '/blog/transport-cpam'
    | '/blog/transport-pmr-personnes-agees'
    | '/blog/vsl-ou-taxi-conventionne'
    | '/chauffeurs/inscription'
    | '/chauffeurs/tarifs'
    | '/hopitaux/$slug'
    | '/maladies/$ald'
    | '/reservation/confirmation'
    | '/tableau-de-bord/chauffeur'
    | '/$department'
    | '/admin'
    | '/blog'
    | '/maladies'
    | '/reservation'
    | '/api/cron/at-risk-bookings'
    | '/api/cron/booking-reminders'
    | '/api/cron/expire-bookings'
    | '/api/cron/expire-driver-trials'
    | '/api/webhooks/stripe'
    | '/tableau-de-bord/chauffeur/compte'
    | '/tableau-de-bord/chauffeur/course/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cgv'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/confirmer-trajet'
    | '/connexion'
    | '/faq'
    | '/mentions-legales'
    | '/mes-reservations'
    | '/mot-de-passe-oublie'
    | '/reinitialiser-mot-de-passe'
    | '/tarifs-cpam'
    | '/villes'
    | '/$department/$city'
    | '/admin/avis'
    | '/admin/chauffeurs'
    | '/admin/journal'
    | '/admin/parametres'
    | '/admin/patients'
    | '/admin/reservations'
    | '/admin/securite'
    | '/admin/statistiques'
    | '/admin_/connexion'
    | '/api/driver-offline-beacon'
    | '/blog/accompagnant-taxi-conventionne'
    | '/blog/ald-transport'
    | '/blog/pmt-prescription'
    | '/blog/retour-domicile-sortie-hopital'
    | '/blog/taxi-conventionne-grossesse'
    | '/blog/taxi-conventionne-sans-avance-frais'
    | '/blog/taxi-sans-prescription'
    | '/blog/traitements-reguliers-taxi-conventionne'
    | '/blog/transport-cpam'
    | '/blog/transport-pmr-personnes-agees'
    | '/blog/vsl-ou-taxi-conventionne'
    | '/chauffeurs/inscription'
    | '/chauffeurs/tarifs'
    | '/hopitaux/$slug'
    | '/maladies/$ald'
    | '/reservation/confirmation'
    | '/tableau-de-bord/chauffeur'
    | '/$department/'
    | '/admin/'
    | '/blog/'
    | '/maladies/'
    | '/reservation/'
    | '/api/cron/at-risk-bookings'
    | '/api/cron/booking-reminders'
    | '/api/cron/expire-bookings'
    | '/api/cron/expire-driver-trials'
    | '/api/webhooks/stripe'
    | '/tableau-de-bord/chauffeur_/compte'
    | '/tableau-de-bord/chauffeur_/course/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CgvRoute: typeof CgvRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConfirmerTrajetRoute: typeof ConfirmerTrajetRoute
  ConnexionRoute: typeof ConnexionRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MesReservationsRoute: typeof MesReservationsRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  TarifsCpamRoute: typeof TarifsCpamRoute
  VillesRoute: typeof VillesRoute
  DepartmentCityRoute: typeof DepartmentCityRoute
  AdminConnexionRoute: typeof AdminConnexionRoute
  ApiDriverOfflineBeaconRoute: typeof ApiDriverOfflineBeaconRoute
  BlogAccompagnantTaxiConventionneRoute: typeof BlogAccompagnantTaxiConventionneRoute
  BlogAldTransportRoute: typeof BlogAldTransportRoute
  BlogPmtPrescriptionRoute: typeof BlogPmtPrescriptionRoute
  BlogRetourDomicileSortieHopitalRoute: typeof BlogRetourDomicileSortieHopitalRoute
  BlogTaxiConventionneGrossesseRoute: typeof BlogTaxiConventionneGrossesseRoute
  BlogTaxiConventionneSansAvanceFraisRoute: typeof BlogTaxiConventionneSansAvanceFraisRoute
  BlogTaxiSansPrescriptionRoute: typeof BlogTaxiSansPrescriptionRoute
  BlogTraitementsReguliersTaxiConventionneRoute: typeof BlogTraitementsReguliersTaxiConventionneRoute
  BlogTransportCpamRoute: typeof BlogTransportCpamRoute
  BlogTransportPmrPersonnesAgeesRoute: typeof BlogTransportPmrPersonnesAgeesRoute
  BlogVslOuTaxiConventionneRoute: typeof BlogVslOuTaxiConventionneRoute
  ChauffeursInscriptionRoute: typeof ChauffeursInscriptionRoute
  ChauffeursTarifsRoute: typeof ChauffeursTarifsRoute
  HopitauxSlugRoute: typeof HopitauxSlugRoute
  MaladiesAldRoute: typeof MaladiesAldRoute
  ReservationConfirmationRoute: typeof ReservationConfirmationRoute
  TableauDeBordChauffeurRoute: typeof TableauDeBordChauffeurRoute
  DepartmentIndexRoute: typeof DepartmentIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MaladiesIndexRoute: typeof MaladiesIndexRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
  ApiCronAtRiskBookingsRoute: typeof ApiCronAtRiskBookingsRoute
  ApiCronBookingRemindersRoute: typeof ApiCronBookingRemindersRoute
  ApiCronExpireBookingsRoute: typeof ApiCronExpireBookingsRoute
  ApiCronExpireDriverTrialsRoute: typeof ApiCronExpireDriverTrialsRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  TableauDeBordChauffeurCompteRoute: typeof TableauDeBordChauffeurCompteRoute
  TableauDeBordChauffeurCourseIdRoute: typeof TableauDeBordChauffeurCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villes': {
      id: '/villes'
      path: '/villes'
      fullPath: '/villes'
      preLoaderRoute: typeof VillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs-cpam': {
      id: '/tarifs-cpam'
      path: '/tarifs-cpam'
      fullPath: '/tarifs-cpam'
      preLoaderRoute: typeof TarifsCpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-reservations': {
      id: '/mes-reservations'
      path: '/mes-reservations'
      fullPath: '/mes-reservations'
      preLoaderRoute: typeof MesReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmer-trajet': {
      id: '/confirmer-trajet'
      path: '/confirmer-trajet'
      fullPath: '/confirmer-trajet'
      preLoaderRoute: typeof ConfirmerTrajetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maladies/': {
      id: '/maladies/'
      path: '/maladies'
      fullPath: '/maladies'
      preLoaderRoute: typeof MaladiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$department/': {
      id: '/$department/'
      path: '/$department'
      fullPath: '/$department'
      preLoaderRoute: typeof DepartmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord/chauffeur': {
      id: '/tableau-de-bord/chauffeur'
      path: '/tableau-de-bord/chauffeur'
      fullPath: '/tableau-de-bord/chauffeur'
      preLoaderRoute: typeof TableauDeBordChauffeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/confirmation': {
      id: '/reservation/confirmation'
      path: '/reservation/confirmation'
      fullPath: '/reservation/confirmation'
      preLoaderRoute: typeof ReservationConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maladies/$ald': {
      id: '/maladies/$ald'
      path: '/maladies/$ald'
      fullPath: '/maladies/$ald'
      preLoaderRoute: typeof MaladiesAldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hopitaux/$slug': {
      id: '/hopitaux/$slug'
      path: '/hopitaux/$slug'
      fullPath: '/hopitaux/$slug'
      preLoaderRoute: typeof HopitauxSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs/tarifs': {
      id: '/chauffeurs/tarifs'
      path: '/chauffeurs/tarifs'
      fullPath: '/chauffeurs/tarifs'
      preLoaderRoute: typeof ChauffeursTarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs/inscription': {
      id: '/chauffeurs/inscription'
      path: '/chauffeurs/inscription'
      fullPath: '/chauffeurs/inscription'
      preLoaderRoute: typeof ChauffeursInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/vsl-ou-taxi-conventionne': {
      id: '/blog/vsl-ou-taxi-conventionne'
      path: '/blog/vsl-ou-taxi-conventionne'
      fullPath: '/blog/vsl-ou-taxi-conventionne'
      preLoaderRoute: typeof BlogVslOuTaxiConventionneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/transport-pmr-personnes-agees': {
      id: '/blog/transport-pmr-personnes-agees'
      path: '/blog/transport-pmr-personnes-agees'
      fullPath: '/blog/transport-pmr-personnes-agees'
      preLoaderRoute: typeof BlogTransportPmrPersonnesAgeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/transport-cpam': {
      id: '/blog/transport-cpam'
      path: '/blog/transport-cpam'
      fullPath: '/blog/transport-cpam'
      preLoaderRoute: typeof BlogTransportCpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/traitements-reguliers-taxi-conventionne': {
      id: '/blog/traitements-reguliers-taxi-conventionne'
      path: '/blog/traitements-reguliers-taxi-conventionne'
      fullPath: '/blog/traitements-reguliers-taxi-conventionne'
      preLoaderRoute: typeof BlogTraitementsReguliersTaxiConventionneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/taxi-sans-prescription': {
      id: '/blog/taxi-sans-prescription'
      path: '/blog/taxi-sans-prescription'
      fullPath: '/blog/taxi-sans-prescription'
      preLoaderRoute: typeof BlogTaxiSansPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/taxi-conventionne-sans-avance-frais': {
      id: '/blog/taxi-conventionne-sans-avance-frais'
      path: '/blog/taxi-conventionne-sans-avance-frais'
      fullPath: '/blog/taxi-conventionne-sans-avance-frais'
      preLoaderRoute: typeof BlogTaxiConventionneSansAvanceFraisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/taxi-conventionne-grossesse': {
      id: '/blog/taxi-conventionne-grossesse'
      path: '/blog/taxi-conventionne-grossesse'
      fullPath: '/blog/taxi-conventionne-grossesse'
      preLoaderRoute: typeof BlogTaxiConventionneGrossesseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/retour-domicile-sortie-hopital': {
      id: '/blog/retour-domicile-sortie-hopital'
      path: '/blog/retour-domicile-sortie-hopital'
      fullPath: '/blog/retour-domicile-sortie-hopital'
      preLoaderRoute: typeof BlogRetourDomicileSortieHopitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/pmt-prescription': {
      id: '/blog/pmt-prescription'
      path: '/blog/pmt-prescription'
      fullPath: '/blog/pmt-prescription'
      preLoaderRoute: typeof BlogPmtPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ald-transport': {
      id: '/blog/ald-transport'
      path: '/blog/ald-transport'
      fullPath: '/blog/ald-transport'
      preLoaderRoute: typeof BlogAldTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/accompagnant-taxi-conventionne': {
      id: '/blog/accompagnant-taxi-conventionne'
      path: '/blog/accompagnant-taxi-conventionne'
      fullPath: '/blog/accompagnant-taxi-conventionne'
      preLoaderRoute: typeof BlogAccompagnantTaxiConventionneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/driver-offline-beacon': {
      id: '/api/driver-offline-beacon'
      path: '/api/driver-offline-beacon'
      fullPath: '/api/driver-offline-beacon'
      preLoaderRoute: typeof ApiDriverOfflineBeaconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/connexion': {
      id: '/admin_/connexion'
      path: '/admin/connexion'
      fullPath: '/admin/connexion'
      preLoaderRoute: typeof AdminConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistiques': {
      id: '/admin/statistiques'
      path: '/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AdminStatistiquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/securite': {
      id: '/admin/securite'
      path: '/securite'
      fullPath: '/admin/securite'
      preLoaderRoute: typeof AdminSecuriteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/journal': {
      id: '/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AdminJournalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chauffeurs': {
      id: '/admin/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/admin/chauffeurs'
      preLoaderRoute: typeof AdminChauffeursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avis': {
      id: '/admin/avis'
      path: '/avis'
      fullPath: '/admin/avis'
      preLoaderRoute: typeof AdminAvisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$department/$city': {
      id: '/$department/$city'
      path: '/$department/$city'
      fullPath: '/$department/$city'
      preLoaderRoute: typeof DepartmentCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord/chauffeur_/compte': {
      id: '/tableau-de-bord/chauffeur_/compte'
      path: '/tableau-de-bord/chauffeur/compte'
      fullPath: '/tableau-de-bord/chauffeur/compte'
      preLoaderRoute: typeof TableauDeBordChauffeurCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/expire-driver-trials': {
      id: '/api/cron/expire-driver-trials'
      path: '/api/cron/expire-driver-trials'
      fullPath: '/api/cron/expire-driver-trials'
      preLoaderRoute: typeof ApiCronExpireDriverTrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/expire-bookings': {
      id: '/api/cron/expire-bookings'
      path: '/api/cron/expire-bookings'
      fullPath: '/api/cron/expire-bookings'
      preLoaderRoute: typeof ApiCronExpireBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/booking-reminders': {
      id: '/api/cron/booking-reminders'
      path: '/api/cron/booking-reminders'
      fullPath: '/api/cron/booking-reminders'
      preLoaderRoute: typeof ApiCronBookingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/at-risk-bookings': {
      id: '/api/cron/at-risk-bookings'
      path: '/api/cron/at-risk-bookings'
      fullPath: '/api/cron/at-risk-bookings'
      preLoaderRoute: typeof ApiCronAtRiskBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord/chauffeur_/course/$id': {
      id: '/tableau-de-bord/chauffeur_/course/$id'
      path: '/tableau-de-bord/chauffeur/course/$id'
      fullPath: '/tableau-de-bord/chauffeur/course/$id'
      preLoaderRoute: typeof TableauDeBordChauffeurCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAvisRoute: typeof AdminAvisRoute
  AdminChauffeursRoute: typeof AdminChauffeursRoute
  AdminJournalRoute: typeof AdminJournalRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminSecuriteRoute: typeof AdminSecuriteRoute
  AdminStatistiquesRoute: typeof AdminStatistiquesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvisRoute: AdminAvisRoute,
  AdminChauffeursRoute: AdminChauffeursRoute,
  AdminJournalRoute: AdminJournalRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminSecuriteRoute: AdminSecuriteRoute,
  AdminStatistiquesRoute: AdminStatistiquesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CgvRoute: CgvRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConfirmerTrajetRoute: ConfirmerTrajetRoute,
  ConnexionRoute: ConnexionRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MesReservationsRoute: MesReservationsRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  TarifsCpamRoute: TarifsCpamRoute,
  VillesRoute: VillesRoute,
  DepartmentCityRoute: DepartmentCityRoute,
  AdminConnexionRoute: AdminConnexionRoute,
  ApiDriverOfflineBeaconRoute: ApiDriverOfflineBeaconRoute,
  BlogAccompagnantTaxiConventionneRoute: BlogAccompagnantTaxiConventionneRoute,
  BlogAldTransportRoute: BlogAldTransportRoute,
  BlogPmtPrescriptionRoute: BlogPmtPrescriptionRoute,
  BlogRetourDomicileSortieHopitalRoute: BlogRetourDomicileSortieHopitalRoute,
  BlogTaxiConventionneGrossesseRoute: BlogTaxiConventionneGrossesseRoute,
  BlogTaxiConventionneSansAvanceFraisRoute:
    BlogTaxiConventionneSansAvanceFraisRoute,
  BlogTaxiSansPrescriptionRoute: BlogTaxiSansPrescriptionRoute,
  BlogTraitementsReguliersTaxiConventionneRoute:
    BlogTraitementsReguliersTaxiConventionneRoute,
  BlogTransportCpamRoute: BlogTransportCpamRoute,
  BlogTransportPmrPersonnesAgeesRoute: BlogTransportPmrPersonnesAgeesRoute,
  BlogVslOuTaxiConventionneRoute: BlogVslOuTaxiConventionneRoute,
  ChauffeursInscriptionRoute: ChauffeursInscriptionRoute,
  ChauffeursTarifsRoute: ChauffeursTarifsRoute,
  HopitauxSlugRoute: HopitauxSlugRoute,
  MaladiesAldRoute: MaladiesAldRoute,
  ReservationConfirmationRoute: ReservationConfirmationRoute,
  TableauDeBordChauffeurRoute: TableauDeBordChauffeurRoute,
  DepartmentIndexRoute: DepartmentIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  MaladiesIndexRoute: MaladiesIndexRoute,
  ReservationIndexRoute: ReservationIndexRoute,
  ApiCronAtRiskBookingsRoute: ApiCronAtRiskBookingsRoute,
  ApiCronBookingRemindersRoute: ApiCronBookingRemindersRoute,
  ApiCronExpireBookingsRoute: ApiCronExpireBookingsRoute,
  ApiCronExpireDriverTrialsRoute: ApiCronExpireDriverTrialsRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  TableauDeBordChauffeurCompteRoute: TableauDeBordChauffeurCompteRoute,
  TableauDeBordChauffeurCourseIdRoute: TableauDeBordChauffeurCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
