/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationIndexRouteImport } from './routes/reservation/index'
import { Route as TableauDeBordChauffeurRouteImport } from './routes/tableau-de-bord/chauffeur'
import { Route as DepartmentCityRouteImport } from './routes/$department.$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIndexRoute = ReservationIndexRouteImport.update({
  id: '/reservation/',
  path: '/reservation/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordChauffeurRoute = TableauDeBordChauffeurRouteImport.update({
  id: '/tableau-de-bord/chauffeur',
  path: '/tableau-de-bord/chauffeur',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentCityRoute = DepartmentCityRouteImport.update({
  id: '/$department/$city',
  path: '/$department/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/reservation': typeof ReservationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/reservation': typeof ReservationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$department/$city': typeof DepartmentCityRoute
  '/tableau-de-bord/chauffeur': typeof TableauDeBordChauffeurRoute
  '/reservation/': typeof ReservationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$department/$city'
    | '/tableau-de-bord/chauffeur'
    | '/reservation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$department/$city' | '/tableau-de-bord/chauffeur' | '/reservation'
  id:
    | '__root__'
    | '/'
    | '/$department/$city'
    | '/tableau-de-bord/chauffeur'
    | '/reservation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepartmentCityRoute: typeof DepartmentCityRoute
  TableauDeBordChauffeurRoute: typeof TableauDeBordChauffeurRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord/chauffeur': {
      id: '/tableau-de-bord/chauffeur'
      path: '/tableau-de-bord/chauffeur'
      fullPath: '/tableau-de-bord/chauffeur'
      preLoaderRoute: typeof TableauDeBordChauffeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$department/$city': {
      id: '/$department/$city'
      path: '/$department/$city'
      fullPath: '/$department/$city'
      preLoaderRoute: typeof DepartmentCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepartmentCityRoute: DepartmentCityRoute,
  TableauDeBordChauffeurRoute: TableauDeBordChauffeurRoute,
  ReservationIndexRoute: ReservationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
